export enum RoutesUrls {
  root = '/lmskgma',
  home = '/lmskgma/home',
  studentBase = '/lmskgma/studentBase',
  employees = '/lmskgma/employees',
  businessTrips = '/lmskgma/businessTrips',
  reports = '/lmskgma/reports',
  items = '/lmskgma/items',
  planNav = '/lmskgma/planNav',
  test = 'lmskgma/test',
  result = 'lmskgma/result',
  login = '/lmskgma/login',
  logout = '/lmskgma/logout',
  settings = '/lmskgma/settings',
  news = '/lmskgma/news',
  plan = '/lmskgma/plan',
  discipline = '/lmskgma/discipline',
  qr = '/lmskgma/qr',
  payment = '/lmskgma/payment',
  order = '/lmskgma/order',
  score = '/lmskgma/score',
  notFound = '/lmskgma/not-found',
}
